server:
  port: 8081 # Set the server port to 8081

spring:
  data:
    mongodb:
      uri: ${MONGODB_URL}

cognito:
  clientId: ${COGNITO_CLIENT_ID}
  client-secret: ${COGNITO_CLIENT_SECRET}

idle:
  timeout:
    day: 3
    hour: 12
    minute: 0
    second: 0

logging:
  level:
    org.springframework.web: INFO
    com.bitsar.passwordlessauth: DEBUG